# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization_type', models.CharField(choices=[('SUPERMARKET', 'Supermarket'), ('FAST-FOOD', 'Fast-Food'), ('SMART-BUILDING', 'Smart Building'), ('CINEMA', 'Cinema')], default='SUPERMARKET', max_length=20)),
                ('country', django_countries.fields.CountryField(default='Israel', max_length=2)),
                ('logo', models.CharField(max_length=1000)),
            ],
        ),
    ]
